version: '3'
services:
  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    volumes:
      - my-app:/my-app/build/  # build files will be added at this directory 

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - my-app:/usr/share/nginx/html/my-app # Copy React App's build files to the Nginx directory

volumes:
   my-app: