# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js '20.x'
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  build-docker-image:
    needs: build-and-test
    name: Build the Docker Image
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2 # London

    steps:
      - name: checkout main
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 992382773706.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build images
        run: |
          docker build -t connectu-user-profile-server ./

      - name: List Docker images (for debugging)
        run: docker images

      - name: Tag images
        run: |
          docker tag connectu-user-profile-server:latest 992382773706.dkr.ecr.eu-west-2.amazonaws.com/connectu-user-profile-server:latest

      - name: Push container
        run: |
          docker push 992382773706.dkr.ecr.eu-west-2.amazonaws.com/connectu-user-profile-server:latest

      - name: Update lambda function
        run: |
          aws lambda update-function-code --function-name connectu-signin-signup --image-uri 992382773706.dkr.ecr.eu-west-2.amazonaws.com/connectu-user-profile-server:latest
